name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main  # or change to dev, staging etc.

jobs:
  deploy:
    name: Deploy Infra
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   # replace with your AWS region

    - name: Deploy CloudFormation Root Stack
      run: |
        aws cloudformation deploy \
          --stack-name MyInfraStack \
          --template-file root-stack.yaml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides Environment=Dev
